obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.35, -0.3], [0.35, 0.3], [-0.35,0.3], [-0.35, -0.3]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.1

obstacles_layer:
  observation_sources: rplidar_laser
  rplidar_laser: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
  
static:
  map_topic: map
  subscribe_to_updates: true
