base_frame: base_link
odom_frame: odom
scan: scan
map_update_interval: 5.0
maxUrange: 8.0
maxRange: 10.0

minimumScore: 200

linearUpdate: 0.5
angularUpdate: 0.01
temporalUpdate: -1.0
resampleThreshold: 0.5
particles: 30
xmin: -1.0
ymin: -1.0
xmax: 1.0
ymax: 1.0

delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005

srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2